In [1]:
import numpy as np

In [5]:
np.cos((np.pi)/2)

6.123233995736766e-17

In [7]:
np.log(5)

1.6094379124341003

In [8]:
np.exp(5)

148.4131591025766

In [9]:
np.log(np.exp(5))

5.0

In [24]:
np.sqrt(784)

28.0

In [33]:
np.arange(0,16,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [34]:
[1,2,3]

[1, 2, 3]

In [36]:
np.array([1,2,3])

array([1, 2, 3])

In [38]:
[[1,2,3],[4,5,6],[7,8,9]]

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [45]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
np.array([[1,2,3],[4,5,6],[7,8,9]]).T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [44]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [47]:
np.arange(0,16,3)

array([ 0,  3,  6,  9, 12, 15])

In [49]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [51]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [53]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [56]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [60]:
np.zeros((5,5,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [62]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [64]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [84]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [87]:
a1=np.array([[1,2,3],[3,2,1],[2,1,3]])
a2=np.array([[3,2,1],[2,3,1],[1,1,3]])
print('a1:\n',a1,'\n','\n','a2:\n',a2,'\n\n')
1/a1

a1:
 [[1 2 3]
 [3 2 1]
 [2 1 3]] 
 
 a2:
 [[3 2 1]
 [2 3 1]
 [1 1 3]] 




array([[1.        , 0.5       , 0.33333333],
       [0.33333333, 0.5       , 1.        ],
       [0.5       , 1.        , 0.33333333]])

In [88]:
np.sqrt(a2)

array([[1.73205081, 1.41421356, 1.        ],
       [1.41421356, 1.73205081, 1.        ],
       [1.        , 1.        , 1.73205081]])

In [81]:
a1=np.array([[1,2,3],[3,2,1],[2,1,3]])
a2=np.array([[3,2,1],[2,3,1],[1,1,3]])
print('a1:\n',a1,'\n','\n','a2:\n',a2,'\n\n')
a1*a2   ### element by element multiplication

a1:
 [[1 2 3]
 [3 2 1]
 [2 1 3]] 
 
 a2:
 [[3 2 1]
 [2 3 1]
 [1 1 3]] 




array([[3, 4, 3],
       [6, 6, 1],
       [2, 1, 9]])

In [89]:
a1=np.array([[1,2,3],[3,2,1],[2,1,3]])
a2=np.array([[3,2,1],[2,3,1],[1,1,3]])
print('a1:\n',a1,'\n','\n','a2:\n',a2,'\n\n')
a3=np.matmul(a1,a2)
print(a3)

a1:
 [[1 2 3]
 [3 2 1]
 [2 1 3]] 
 
 a2:
 [[3 2 1]
 [2 3 1]
 [1 1 3]] 


[[10 11 12]
 [14 13  8]
 [11 10 12]]


In [95]:
np.linalg.solve(a1,a3)

array([[3., 2., 1.],
       [2., 3., 1.],
       [1., 1., 3.]])

In [101]:
a1=np.array([[1,2,3],[3,2,1],[2,1,3]])
a2=np.linalg.inv(a1)
a3=np.matmul(a2,a1)
a3

array([[ 1.00000000e+00,  0.00000000e+00, -2.22044605e-16],
       [ 0.00000000e+00,  1.00000000e+00,  4.44089210e-16],
       [ 0.00000000e+00, -5.55111512e-17,  1.00000000e+00]])

In [104]:
## matmul works conventional way 2D matrices
a1=np.array([[1,2],[3,2]])
a2=np.linalg.inv(a1)
a3=np.matmul(a1,a2)
a3

array([[1.00000000e+00, 5.55111512e-17],
       [0.00000000e+00, 1.00000000e+00]])

In [106]:
a1=np.random.rand(5,5)
a1

array([[0.86667226, 0.60072711, 0.20743134, 0.82370877, 0.12149193],
       [0.01465987, 0.73000012, 0.71207915, 0.98832817, 0.85649717],
       [0.74547313, 0.50645404, 0.96414763, 0.54962787, 0.6678751 ],
       [0.07779238, 0.91933114, 0.42745352, 0.52856379, 0.24622438],
       [0.2064235 , 0.95611453, 0.44520531, 0.70386566, 0.17056742]])

In [109]:
a1=np.random.randn(25)
a1

array([-0.06115616,  0.41471485, -0.26704988, -0.42079751, -1.21927754,
        0.76849339, -0.84722975,  0.27091497, -0.737587  , -1.11878425,
       -0.75073526,  1.8855016 ,  0.60228556,  0.95153981,  1.57876828,
        1.21373691, -0.97954436, -0.26916765, -1.246027  ,  0.79926108,
        0.75765055, -0.82870943,  0.66799085, -0.97148412,  0.67966023])

In [114]:
a1[range(15,4,-3)]

array([ 1.21373691,  0.60228556, -1.11878425, -0.84722975])

In [115]:
a1.mean()

0.03491872836002429

In [116]:
a1.std()

0.9109644222469144

In [117]:
a1.max()

1.885501601785782

In [118]:
a1.min()

-1.2460270015255142

In [119]:
np.mean(a1)

0.03491872836002429

In [120]:
np.std(a1)

0.9109644222469144

In [121]:
np.max(a1)

1.885501601785782

In [122]:
np.min(a1)

-1.2460270015255142

In [126]:
a1=np.random.randn(5,5)
a1

array([[-0.86710921, -1.5270925 ,  0.64610737, -0.1615069 , -0.8061541 ],
       [ 0.27263192, -1.0436439 ,  2.63690619, -0.03932351, -0.03222815],
       [-1.30897805,  1.06843858, -0.27941432, -0.57602664,  0.89413265],
       [-0.47180919, -0.03948538, -0.30836744,  0.67967182,  0.26582818],
       [-0.9252695 , -0.29851034,  1.12752943, -0.68755703, -0.0712831 ]])

In [124]:
a2=a1[1:3,1:3]
a2

array([[ 0.98853812,  1.43394287],
       [ 1.38734429, -0.70719796]])

In [125]:
a2[:]=6
a1

array([[ 1.12126636, -0.81201837,  1.90294263, -0.93321018,  0.03613347],
       [ 0.78212181,  6.        ,  6.        , -0.54007207,  0.19485691],
       [-1.68532406,  6.        ,  6.        ,  0.43307329,  0.42596281],
       [-1.98745174,  0.84161306, -0.5865289 ,  0.78645262,  0.29218977],
       [ 0.3246907 ,  1.08092986,  0.79538752,  0.27322993, -0.42168028]])

In [127]:
a2=a1[1:3,1:3].copy()
a2[:]=6
a1

array([[-0.86710921, -1.5270925 ,  0.64610737, -0.1615069 , -0.8061541 ],
       [ 0.27263192, -1.0436439 ,  2.63690619, -0.03932351, -0.03222815],
       [-1.30897805,  1.06843858, -0.27941432, -0.57602664,  0.89413265],
       [-0.47180919, -0.03948538, -0.30836744,  0.67967182,  0.26582818],
       [-0.9252695 , -0.29851034,  1.12752943, -0.68755703, -0.0712831 ]])

In [128]:
a2

array([[6., 6.],
       [6., 6.]])

In [129]:
a1>0

array([[False, False,  True, False, False],
       [ True, False,  True, False, False],
       [False,  True, False, False,  True],
       [False, False, False,  True,  True],
       [False, False,  True, False, False]])

In [130]:
a1[a1>0]

array([0.64610737, 0.27263192, 2.63690619, 1.06843858, 0.89413265,
       0.67967182, 0.26582818, 1.12752943])

In [137]:
import pandas as pd
a1=pd.DataFrame(np.random.randn(5,5))
a1

0         1         2         3         4
0 -1.225081 -0.496622 -1.972245  0.239537 -0.445069
1  0.503279  1.016830  1.016718 -0.096317  0.579864
2  1.178766  0.611142 -0.924764  0.054178 -3.295443
3  1.407365  1.420235 -1.001219  0.885313  1.434079
4  0.147853 -1.225087  0.441595  0.073976 -1.502215

In [138]:
a1>0 

0      1      2      3      4
0  False  False  False   True  False
1   True   True   True  False   True
2   True   True  False   True  False
3   True   True  False   True   True
4   True  False   True   True  False

In [139]:
a1[a1>0]

0         1         2         3         4
0       NaN       NaN       NaN  0.239537       NaN
1  0.503279  1.016830  1.016718       NaN  0.579864
2  1.178766  0.611142       NaN  0.054178       NaN
3  1.407365  1.420235       NaN  0.885313  1.434079
4  0.147853       NaN  0.441595  0.073976       NaN

In [140]:
df3 = pd.DataFrame(np.random.randn(5,5),index=['first row','second row','third row','fourth row','fifth row'],
                   columns=['first col','second col','third col','fourth col','fifth col'])
df3

first col  second col  third col  fourth col  fifth col
first row   -0.015474   -0.150653  -0.865325    0.194477  -0.368993
second row   0.213811   -0.500977   0.885736    1.048016  -2.231234
third row    0.367162   -1.600930  -1.332241    0.696708   1.489130
fourth row  -1.325607   -0.352438  -0.858007   -0.776900  -1.583628
fifth row    0.660604   -0.211639   0.264064   -1.226755  -1.561711

In [151]:
df3.loc['first row':'fifth row','first col':'fourth col']

first col  second col  third col  fourth col
first row   -0.015474   -0.150653  -0.865325    0.194477
second row   0.213811   -0.500977   0.885736    1.048016
third row    0.367162   -1.600930  -1.332241    0.696708
fourth row  -1.325607   -0.352438  -0.858007   -0.776900
fifth row    0.660604   -0.211639   0.264064   -1.226755

In [153]:
df3.loc['first row':'fifth row',['first col','fourth col']]

first col  fourth col
first row   -0.015474    0.194477
second row   0.213811    1.048016
third row    0.367162    0.696708
fourth row  -1.325607   -0.776900
fifth row    0.660604   -1.226755

In [156]:
df7=pd.DataFrame({"customer":['101','102','103','104'], 
                    'category': ['cat2','cat2','cat1','cat3'],
                    'important': ['yes','no','yes','yes'],
                    'sales': [123,52,214,663]})
df8=pd.DataFrame({"customer":['101','103','104','105'], 
                    'color': ['yellow','green','green','blue'],
                    'distance': [12,9,44,21],
                    'sales': [123,214,663,331]})
df7

customer category important  sales
0      101     cat2       yes    123
1      102     cat2        no     52
2      103     cat1       yes    214
3      104     cat3       yes    663

In [157]:
df8

customer   color  distance  sales
0      101  yellow        12    123
1      103   green         9    214
2      104   green        44    663
3      105    blue        21    331

In [158]:
pd.concat([df7,df8],axis=0,sort=False)

customer category important  sales   color  distance
0      101     cat2       yes    123     NaN       NaN
1      102     cat2        no     52     NaN       NaN
2      103     cat1       yes    214     NaN       NaN
3      104     cat3       yes    663     NaN       NaN
0      101      NaN       NaN    123  yellow      12.0
1      103      NaN       NaN    214   green       9.0
2      104      NaN       NaN    663   green      44.0
3      105      NaN       NaN    331    blue      21.0

In [160]:
pd.concat([df7,df8],axis=1,sort=False)

customer category important  sales customer   color  distance  sales
0      101     cat2       yes    123      101  yellow        12    123
1      102     cat2        no     52      103   green         9    214
2      103     cat1       yes    214      104   green        44    663
3      104     cat3       yes    663      105    blue        21    331

In [161]:
pd.merge(df7,df8,how='outer',on='customer')

customer category important  sales_x   color  distance  sales_y
0      101     cat2       yes    123.0  yellow      12.0    123.0
1      102     cat2        no     52.0     NaN       NaN      NaN
2      103     cat1       yes    214.0   green       9.0    214.0
3      104     cat3       yes    663.0   green      44.0    663.0
4      105      NaN       NaN      NaN    blue      21.0    331.0

In [162]:
pd.merge(df7,df8,how='inner',on='customer')

customer category important  sales_x   color  distance  sales_y
0      101     cat2       yes      123  yellow        12      123
1      103     cat1       yes      214   green         9      214
2      104     cat3       yes      663   green        44      663

In [177]:
df1=pd.merge(df7,df8,how='right',on='customer')
df1

customer category important  sales_x   color  distance  sales_y
0      101     cat2       yes    123.0  yellow        12      123
1      103     cat1       yes    214.0   green         9      214
2      104     cat3       yes    663.0   green        44      663
3      105      NaN       NaN      NaN    blue        21      331

In [191]:
def half(x):
    return x/2
a1=pd.DataFrame(np.random.randn(5,5))
a1.applymap(half)
a1

0         1         2         3         4
0 -0.510984  0.025497  1.362976  2.015142 -0.473563
1 -0.210871 -1.501843 -0.112266 -1.313572  0.636275
2  1.482223  0.497741  0.864244 -0.848477 -0.857084
3 -0.010049 -0.434787 -0.386221  2.118200 -0.195548
4  0.679526 -1.264149  0.619161  0.690488 -0.957333

In [193]:
a1[0].apply(half)

0   -0.255492
1   -0.105436
2    0.741111
3   -0.005025
4    0.339763
Name: 0, dtype: float64

In [194]:
sum(a1[0])

1.429844785581239

In [197]:
a1[0].sum()

1.429844785581239

In [198]:
mydict = {'customer': ['Customer 1','Customer 1','Customer2','Customer2','Customer3','Customer3'], 
          'product1': [1.1,2.1,3.8,4.2,5.5,6.9],
          'product2': [8.2,9.1,11.1,5.2,44.66,983]}
df6 = pd.DataFrame(mydict,index=['Purchase 1','Purchase 2','Purchase 3','Purchase 4','Purchase 5','Purchase 6'])
df6

customer  product1  product2
Purchase 1  Customer 1       1.1      8.20
Purchase 2  Customer 1       2.1      9.10
Purchase 3   Customer2       3.8     11.10
Purchase 4   Customer2       4.2      5.20
Purchase 5   Customer3       5.5     44.66
Purchase 6   Customer3       6.9    983.00

In [199]:
grouped_data = df6.groupby('customer')
print(grouped_data)

In [201]:
(grouped_data).std()

product1    product2
customer                        
Customer 1  0.707107    0.636396
Customer2   0.282843    4.171930
Customer3   0.989949  663.506577

In [202]:
df8.to_csv('df8.csv',index=True)

In [203]:
new_df8 = pd.read_csv('df8.csv',index_col=0)
new_df8

customer   color  distance  sales
0       101  yellow        12    123
1       103   green         9    214
2       104   green        44    663
3       105    blue        21    331

In [204]:
df8.to_excel('df8.xlsx',index=False,sheet_name='first sheet')
newer_df8 = pd.read_excel('df8.xlsx',sheet_name='first sheet',index_col=1)
newer_df8

customer  distance  sales
color                            
yellow       101        12    123
green        103         9    214
green        104        44    663
blue         105        21    331