In [9]:
#few functions
import numpy as np
print(np.cos((np.pi)/2)) #my observation: value in output is tending towards zero
print(np.sqrt(9))
print(np.log(np.exp(40)))

6.123233995736766e-17
3.0
40.0


In [23]:
#transpose of a matrix
import numpy as np
l1=[[1,2,3],[4,5,6],[7,8,9]]
a1=np.array(l1)
print(a1.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [14]:
#arange() method of NumPy
import numpy as np
a1=np.arange(0,6)
print(a1)
a2=np.arange(3,21,6)
print(a2)

[0 1 2 3 4 5]
[ 3  9 15]


In [1]:
#linspace() and reshape()
import numpy as np
a1=np.linspace(0,5,5)
print(a1.reshape(5,1))
print(a1)
a2=a1.reshape(5,1)
print(a2)

[[0.  ]
 [1.25]
 [2.5 ]
 [3.75]
 [5.  ]]
[0.   1.25 2.5  3.75 5.  ]
[[0.  ]
 [1.25]
 [2.5 ]
 [3.75]
 [5.  ]]


In [2]:
#checking datatypes
import numpy as np
l1=[1,2,3.0]
print(type(l1[0]))
a1=np.array(l1)
print(type(a1[0]))

<class 'int'>
<class 'numpy.float64'>


In [43]:
#zeros()
import numpy as np
a1=np.zeros(5)
print(a1)
a2=np.zeros([5,3])
print(a2)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [46]:
#ones(), eye()
import numpy as np
a1=np.ones(5)
print(a1)
a2=np.ones([5,3])
print(a2)
a3=np.eye(7) #identity matrix
print(a3)

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [7]:
#element by element addition, multiplication, subtraction, division, inverse and squareroot
import numpy as np
a1=np.arange(1,6)
a2=np.arange(3,8)
print(a1)
print(a2)
print(a1+a2)
print(a1/a2)
print(1/a1)
print(np.sqrt(a2))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[0.33333333 0.5        0.6        0.66666667 0.71428571]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [12]:
#matrix multiplication
import numpy as np
a1=np.array([[1,2,1],[4,5,9],[1,8,9]])
a2=np.array([1,2,2])
product=np.matmul(a1,a2)
print(product)
print(np.linalg.solve(a1,product))
print(np.linalg.solve(a1,a2))   #wont give 'product' as result  #it is not division

[ 7 32 35]
[1. 2. 2.]
[ 0.38888889  0.38888889 -0.16666667]


In [22]:
#inverse
import numpy as np
a1=np.array([[4,3],[3,2]])
a2=np.linalg.inv(a1)
print(a2)
print(np.matmul(a1,a2))
a3=np.array([[3,4],[1,2]])
a4=np.linalg.inv(a3)
print(a4)
print(np.matmul(a3,a4))
#MY INFERENCE:
#matmul defers from dot operation of matrices
#if both are 2d matrices, they are multiplied the conventional way
#https://numpy.org/doc/stable/reference/generated/numpy.matmul.html
#refer above link for more

[[-2.  3.]
 [ 3. -4.]]
[[1. 0.]
 [0. 1.]]
[[ 1.  -2. ]
 [-0.5  1.5]]
[[1.00000000e+00 0.00000000e+00]
 [1.11022302e-16 1.00000000e+00]]


In [24]:
#unique values in an array
a1=np.array([6,'Red','red','purple','green','red','purple'])
print(np.unique(a1))
print(type(np.unique(a1)))

['6' 'Red' 'green' 'purple' 'red']
<class 'numpy.ndarray'>


In [22]:
#random values in matrix
import numpy as np
a1=np.random.rand(5,5) #values range from 0 to 1
print(a1)

[[0.19575706 0.33754746 0.60896183 0.02331012 0.04988548]
 [0.84658438 0.83862886 0.74926246 0.0416831  0.76135821]
 [0.74313661 0.49598925 0.70646211 0.48116889 0.30720481]
 [0.76178269 0.21827554 0.1937777  0.18970282 0.93965127]
 [0.10124201 0.52294624 0.98333868 0.8835475  0.18287453]]


In [16]:
#random values in matrix
import numpy as np
a1=np.random.randn(5,5) #values are standard normal variables
print(a1)

[[-0.17297007  0.27699557 -0.26956112  1.01593288  0.55500232]
 [ 0.39091864  1.87355255 -0.89970368 -0.05380736 -0.7744677 ]
 [-0.24660371 -0.89705086 -0.38690871 -1.41199474  0.72561793]
 [ 0.09182822  1.04979442 -1.01425514 -1.75340436  0.49801342]
 [ 2.44363031 -0.61583308  0.31151614 -0.10489613 -0.59129014]]


In [25]:
#mean(), std(), max(), min()
import numpy as np
a1=np.random.randn(5,5)
print(a1)
print(np.mean(a1))
print(np.std(a1))
print(np.max(a1))
print(np.min(a1))

[[ 0.89504695  0.01836041 -0.31111975  1.571622   -0.64436768]
 [-0.75245057  0.2749153   0.34239873 -0.29772586  0.30900128]
 [-0.56696219  0.55832149 -1.30451496 -0.59951454 -0.89776678]
 [-0.61867111 -0.81751848  1.37572338 -0.15943592 -0.43504591]
 [ 0.91648944  0.03004758  0.75995777  0.92880296  0.53322218]]
0.044352628552452415
0.7456943437769167
1.5716220025255023
-1.3045149553087998


In [33]:
#accessing entries in Vectors
import numpy as np
a1=np.random.randn(15)
print(a1,'\n')
print(a1[3],'\n')
print(a1[1:4],'\n')

#using arange()
a2=np.arange(0,15,3)
print(a2,'\n')
print(a1[a2])

[-0.29429226  0.54504863  2.44917551  0.96203651 -1.07004372 -1.19199625
  0.46684973  0.09509717  0.81663101  0.67976715 -1.26744761  0.57568553
  1.07242385  1.0046394  -0.7973031 ] 

0.9620365112356447 

[0.54504863 2.44917551 0.96203651] 

[ 0  3  6  9 12] 

[-0.29429226  0.96203651  0.46684973  0.67976715  1.07242385]


In [44]:
#accessing entries in Matrices
import numpy as np
a1=np.random.randn(5,5)
print(a1,'\n')
print(a1[1,2],'\n')
print(a1[1][2],'\n')
print(a1[1:3,2:4])

[[ 0.7214259  -0.51481025 -0.16254156  0.0101744   0.83742236]
 [ 0.88678999 -0.57516775  0.37371524 -0.23545103 -1.27342271]
 [ 1.49320316 -1.24619352  0.80658799  0.64400562  0.86740252]
 [-0.48649597  0.01270934 -0.25105387 -2.57735471 -1.75389425]
 [-0.1175542   0.63504708 -0.50735696  1.07351807  1.10072362]] 

0.37371524418827684 

0.37371524418827684 

[[ 0.37371524 -0.23545103]
 [ 0.80658799  0.64400562]]


In [47]:
#changing entries in array
import numpy as np
a1=np.random.rand(15)
print(a1,'\n')
a1[3:7]=1
print(a1,'\n')
a1[3:7]=[6,4,7,3]
print(a1,'\n')

[0.615597   0.47399923 0.3018716  0.70793606 0.17808797 0.55320148
 0.5333445  0.57862381 0.56614802 0.52282176 0.7593011  0.3828625
 0.83047613 0.30673985 0.2926469 ] 

[0.615597   0.47399923 0.3018716  1.         1.         1.
 1.         0.57862381 0.56614802 0.52282176 0.7593011  0.3828625
 0.83047613 0.30673985 0.2926469 ] 

[0.615597   0.47399923 0.3018716  6.         4.         7.
 3.         0.57862381 0.56614802 0.52282176 0.7593011  0.3828625
 0.83047613 0.30673985 0.2926469 ] 



In [51]:
#changing entries in Matrices
import numpy as np
a1=np.random.randn(5,5)
print(a1,'\n')
a1[1:3,3:5]=0
print(a1,'\n')
a1[1:3,3:5]=[1,2]
print(a1,'\n')
a1[1:3,3:5]=[[1,2],[3,4]]
print(a1,'\n')

[[-2.09931825  0.07628597 -0.62507972  1.10936387  1.24653093]
 [-0.85322239  2.53815132 -1.00953734  1.31737579  0.11480654]
 [ 2.71215839  1.19016259 -0.34223626 -0.74204048  0.71827954]
 [ 0.98428622 -0.07068303  1.36330067 -0.44009914 -1.57183567]
 [-1.86825987  1.28822148 -1.60722212  1.50499736  0.28365446]] 

[[-2.09931825  0.07628597 -0.62507972  1.10936387  1.24653093]
 [-0.85322239  2.53815132 -1.00953734  0.          0.        ]
 [ 2.71215839  1.19016259 -0.34223626  0.          0.        ]
 [ 0.98428622 -0.07068303  1.36330067 -0.44009914 -1.57183567]
 [-1.86825987  1.28822148 -1.60722212  1.50499736  0.28365446]] 

[[-2.09931825  0.07628597 -0.62507972  1.10936387  1.24653093]
 [-0.85322239  2.53815132 -1.00953734  1.          2.        ]
 [ 2.71215839  1.19016259 -0.34223626  1.          2.        ]
 [ 0.98428622 -0.07068303  1.36330067 -0.44009914 -1.57183567]
 [-1.86825987  1.28822148 -1.60722212  1.50499736  0.28365446]] 

[[-2.09931825  0.07628597 -0.62507972  1.10936

In [54]:
#lists
a1=[1,2,3,4,5]
a2=a1
a2[2]=7
print(a2,'\n')
print(a1,'\n')      #value gets updated in a1 as well

l1=[1,2,3,4,5]
l2=l1[1:4]
print(l2,'\n')
l2[2]=7
print(l2,'\n')
print(l1,'\n')      #value doesnt get updated in l1

[1, 2, 7, 4, 5] 

[1, 2, 7, 4, 5] 

[2, 3, 4] 

[2, 3, 7] 

[1, 2, 3, 4, 5] 



In [62]:
#sub matrices
import numpy as np
mat=np.random.randn(5,5)
print(mat,'\n')
sub_mat=mat[1:3,3:5]
print(sub_mat,'\n')
sub_mat[:]=6
print(sub_mat,'\n')
print(mat,'\n')       #values get updated in main matrix mat as well
sub_mat2=mat[2:4,1:3].copy()
sub_mat2[0][0]=0
print(sub_mat2,'\n')
print(mat,'\n')       #value doesnt get updated in main matrix mat

[[ 0.56707783  0.46076799  1.24901425 -0.7315659  -0.14547452]
 [-0.84730058 -0.56513702 -0.79729569  0.11116672 -1.22344863]
 [-0.74310964  1.73005895  0.16155449  1.55526726  0.06671693]
 [-1.45272661 -0.56711269  0.12714724 -0.46650484 -0.35225822]
 [-0.94948965 -0.40679039  1.27012069  1.16521717  0.88203756]] 

[[ 0.11116672 -1.22344863]
 [ 1.55526726  0.06671693]] 

[[6. 6.]
 [6. 6.]] 

[[ 0.56707783  0.46076799  1.24901425 -0.7315659  -0.14547452]
 [-0.84730058 -0.56513702 -0.79729569  6.          6.        ]
 [-0.74310964  1.73005895  0.16155449  6.          6.        ]
 [-1.45272661 -0.56711269  0.12714724 -0.46650484 -0.35225822]
 [-0.94948965 -0.40679039  1.27012069  1.16521717  0.88203756]] 

[[ 0.          0.16155449]
 [-0.56711269  0.12714724]] 

[[ 0.56707783  0.46076799  1.24901425 -0.7315659  -0.14547452]
 [-0.84730058 -0.56513702 -0.79729569  6.          6.        ]
 [-0.74310964  1.73005895  0.16155449  6.          6.        ]
 [-1.45272661 -0.56711269  0.12714724 -0

In [69]:
#Pandas: Series
import pandas as pd
l1=[1,2,3,4,5]
n1=np.array(l1)
p1=pd.Series(l1)
print(p1,'\n')
p2=pd.Series(n1)
print(p2,'\n')

l2=[5,6,7,8,9]
n2=np.array(l2)
p3=pd.Series(data=l2)
print(p3,'\n')
p4=pd.Series(data=n2)
print(p4,'\n')

0    1
1    2
2    3
3    4
4    5
dtype: int64 

0    1
1    2
2    3
3    4
4    5
dtype: int32 

0    5
1    6
2    7
3    8
4    9
dtype: int64 

0    5
1    6
2    7
3    8
4    9
dtype: int32 



In [81]:
#accessing series and adding labels
l1=[1,2,3,4,5]
n1=np.array(l1)
mylabels=['1st','2nd','3rd','4th','5th']
p1=pd.Series(data=n1,index=mylabels)
print(p1,'\n')
p2=pd.Series(n1,mylabels)
print(p2,'\n')
print(p1[2])
print(p2['3rd'])

1st    1
2nd    2
3rd    3
4th    4
5th    5
dtype: int32 

1st    1
2nd    2
3rd    3
4th    4
5th    5
dtype: int32 

3
3


In [44]:
#maths operations and concat()
l1=[1,2,3,4,5]
n1=np.array(l1)
mylabels=['1st','2nd','3rd','4th','5th']
p1=pd.Series(n1,mylabels)
p2=pd.Series([1,2,3,4,5],['2nd','3rd','4th','5th','6th'])
print(p1,'\n')
print(p2,'\n')
print(p1+p2,'\n')
p3=pd.concat([p1,p2],axis=1)
print(p3,'\n')
print(type(p3))

1st    1
2nd    2
3rd    3
4th    4
5th    5
dtype: int32 

2nd    1
3rd    2
4th    3
5th    4
6th    5
dtype: int64 

1st    NaN
2nd    3.0
3rd    5.0
4th    7.0
5th    9.0
6th    NaN
dtype: float64 

       0    1
1st  1.0  NaN
2nd  2.0  1.0
3rd  3.0  2.0
4th  4.0  3.0
5th  5.0  4.0
6th  NaN  5.0 

<class 'pandas.core.frame.DataFrame'>


In [42]:
#maths operations, concat() and sort
import numpy as np
import pandas as pd
l1=[1,2,3,4,5]
n1=np.array(l1)
mylabels=['first','second','third','fourth','fifth']
p1=pd.Series(n1,mylabels)
p2=pd.Series([1,2,3,4,5],['second','third','fourth','fifth','sixth'])
print(p2+p1,'\n')
print(pd.concat([p1,p2],axis=1),'\n')
print(type(pd.concat([p1,p2],axis=1)),'\n')
print(pd.concat([p1,p2],axis=1,sort=False),'\n')
print(pd.concat([p1,p2],axis=1,sort=True),'\n')
print(pd.concat([p1,p2],axis=0),'\n')
print(pd.concat([p1,p2],axis=0,sort=False),'\n')
print(pd.concat([p1,p2],axis=0,sort=True),'\n')

fifth     9.0
first     NaN
fourth    7.0
second    3.0
sixth     NaN
third     5.0
dtype: float64 

          0    1
first   1.0  NaN
second  2.0  1.0
third   3.0  2.0
fourth  4.0  3.0
fifth   5.0  4.0
sixth   NaN  5.0 

<class 'pandas.core.frame.DataFrame'> 

          0    1
first   1.0  NaN
second  2.0  1.0
third   3.0  2.0
fourth  4.0  3.0
fifth   5.0  4.0
sixth   NaN  5.0 

          0    1
fifth   5.0  4.0
first   1.0  NaN
fourth  4.0  3.0
second  2.0  1.0
sixth   NaN  5.0
third   3.0  2.0 

first     1
second    2
third     3
fourth    4
fifth     5
second    1
third     2
fourth    3
fifth     4
sixth     5
dtype: int64 

first     1
second    2
third     3
fourth    4
fifth     5
second    1
third     2
fourth    3
fifth     4
sixth     5
dtype: int64 

first     1
second    2
third     3
fourth    4
fifth     5
second    1
third     2
fourth    3
fifth     4
sixth     5
dtype: int64 



In [50]:
#creating new DataFrames, labelling, accessing, .loc()
import numpy as np
import pandas as pd
df1=pd.DataFrame([[1,3],[3,4]])
print(df1,'\n')
df2=pd.DataFrame(np.array([[1,2],[3,4]]))
print(df2,'\n')
df3=pd.DataFrame(np.random.randn(5))
print(df3,'\n')
df3=pd.DataFrame(np.random.randn(5,5))
print(df3,'\n')
df4=pd.DataFrame(np.random.randn(3,3),index=['1st','2nd','3rd'],columns=['1','2','3'])
print(df4,'\n')
print(df3[1],'\n')
print(df3[1][2],'\n')
print(df4['1'],'\n')
print(df4['1']['1st'],'\n')
print(df3.loc[2],'\n')
print(df4.loc['2nd'],'\n')
print(df3.loc[[2,4],[1,3]],'\n')
df3.iloc[0,1]

   0  1
0  1  3
1  3  4 

   0  1
0  1  2
1  3  4 

          0
0 -0.666525
1 -0.616231
2  1.927533
3 -0.110329
4 -1.809259 

          0         1         2         3         4
0 -0.662015  1.272222 -0.422423 -1.169802 -0.745285
1  0.801612 -0.542028  1.517311 -1.646831  0.008213
2  1.311799  2.045649  0.185268 -0.074186 -1.040743
3 -0.307192  1.698452 -0.637861  0.706584 -1.804137
4 -0.763920  0.021133 -1.526027  0.457467 -0.656270 

            1         2         3
1st -0.441179  0.391388  1.647655
2nd  0.236839 -0.650910 -0.339476
3rd -0.057256 -0.297572  0.358152 

0    1.272222
1   -0.542028
2    2.045649
3    1.698452
4    0.021133
Name: 1, dtype: float64 

2.0456493047943614 

1st   -0.441179
2nd    0.236839
3rd   -0.057256
Name: 1, dtype: float64 

-0.4411789032421379 

0    1.311799
1    2.045649
2    0.185268
3   -0.074186
4   -1.040743
Name: 2, dtype: float64 

1    0.236839
2   -0.650910
3   -0.339476
Name: 2nd, dtype: float64 

          1         3
2  2.045649 -0.074186

1.2722220949091423

In [2]:
#logical indexing
import numpy as np
import pandas as pd
df1=pd.DataFrame(np.random.randn(5,5),index=['1st','2nd','3rd','4th','5th'],columns=['a','b','c','d','e'])
print(df1,'\n')
print(df1>0,'\n')
print(df1['a']>0,'\n')
print(type(df1>0),'\n')
print(df1[df1>0],'\n')
print(type(df1[df1>0]),'\n')

            a         b         c         d         e
1st -0.993223  0.603620  1.520183  0.782723  1.962294
2nd  0.499278 -2.233492  0.631872 -0.390354 -0.139765
3rd -0.061218  0.915084 -0.282794 -1.767424 -0.288485
4th -0.591390  1.146086 -0.580032  0.094599  0.198006
5th  0.799207 -0.006021 -0.508863  0.196085  0.487984 

         a      b      c      d      e
1st  False   True   True   True   True
2nd   True  False   True  False  False
3rd  False   True  False  False  False
4th  False   True  False   True   True
5th   True  False  False   True   True 

1st    False
2nd     True
3rd    False
4th    False
5th     True
Name: a, dtype: bool 

<class 'pandas.core.frame.DataFrame'> 

            a         b         c         d         e
1st       NaN  0.603620  1.520183  0.782723  1.962294
2nd  0.499278       NaN  0.631872       NaN       NaN
3rd       NaN  0.915084       NaN       NaN       NaN
4th       NaN  1.146086       NaN  0.094599  0.198006
5th  0.799207       NaN       NaN  0.196

In [10]:
#adding columns to dataframe
import numpy as np
import pandas as pd
df1=pd.DataFrame(np.random.randn(5,5),index=['1st','2nd','3rd','4th','5th'],columns=['a','b','c','d','e'])
print(df1,'\n')
df1['f']=np.random.randn(5,1)
print(df1,'\n')

            a         b         c         d         e
1st -0.594506 -1.433531 -0.149242 -0.465234  1.633911
2nd  0.682253  0.587044 -0.432749 -0.269756  1.409683
3rd  1.151067 -0.145451  0.110687 -0.440426 -0.069114
4th -0.255920  0.773753  0.717399  1.953538  1.404616
5th -0.148643 -1.873185  1.424320  1.192554 -0.679387 

            a         b         c         d         e         f
1st -0.594506 -1.433531 -0.149242 -0.465234  1.633911  0.669186
2nd  0.682253  0.587044 -0.432749 -0.269756  1.409683  1.195138
3rd  1.151067 -0.145451  0.110687 -0.440426 -0.069114 -1.353607
4th -0.255920  0.773753  0.717399  1.953538  1.404616  0.915555
5th -0.148643 -1.873185  1.424320  1.192554 -0.679387 -0.109482 



In [17]:
#dropping columns
import numpy as np
import pandas as pd
df1=pd.DataFrame(np.random.randn(5,5),index=['1st','2nd','3rd','4th','5th'],columns=['a','b','c','d','e'])
print(df1.drop('a',axis=1),'\n')
print(df1,'\n')
df1=df1.drop('a',axis=1)
print(df1,'\n')
print(df1.drop('1st',axis=0))
print(df1,'\n')
df1=df1.drop('1st',axis=0)
print(df1,'\n')

            b         c         d         e
1st -0.169907  1.172156 -0.380432  1.168368
2nd -0.385273 -1.014040 -0.018451 -0.336611
3rd -2.644238 -0.769057  2.926259 -0.019425
4th  0.259045 -0.051017  0.248426  0.857486
5th -0.758239  0.060998 -0.671356 -0.283324 

            a         b         c         d         e
1st -0.263773 -0.169907  1.172156 -0.380432  1.168368
2nd  2.516563 -0.385273 -1.014040 -0.018451 -0.336611
3rd  0.137276 -2.644238 -0.769057  2.926259 -0.019425
4th -2.160906  0.259045 -0.051017  0.248426  0.857486
5th  0.126090 -0.758239  0.060998 -0.671356 -0.283324 

            b         c         d         e
1st -0.169907  1.172156 -0.380432  1.168368
2nd -0.385273 -1.014040 -0.018451 -0.336611
3rd -2.644238 -0.769057  2.926259 -0.019425
4th  0.259045 -0.051017  0.248426  0.857486
5th -0.758239  0.060998 -0.671356 -0.283324 

            b         c         d         e
2nd -0.385273 -1.014040 -0.018451 -0.336611
3rd -2.644238 -0.769057  2.926259 -0.019425
4th  0.259

In [26]:
#rest_index()
import numpy as np
import pandas as pd
df1=pd.DataFrame(np.random.randn(5,5),index=['1st','2nd','3rd','4th','5th'],columns=['a','b','c','d','e'])
print(df1.reset_index(),'\n')
print(df1,'\n')
df1=df1.reset_index()
print(df1,'\n')

  index         a         b         c         d         e
0   1st -2.265936 -1.657913 -1.548239 -1.010342 -0.670365
1   2nd  0.245164  1.347530 -0.861760  0.065240  0.005120
2   3rd -0.202618  0.065341 -0.768141  1.011570 -0.963761
3   4th  0.074309  1.732945 -0.793758 -0.636165 -0.883917
4   5th  0.378552 -0.541739  0.673559  1.352167  1.087960 

            a         b         c         d         e
1st -2.265936 -1.657913 -1.548239 -1.010342 -0.670365
2nd  0.245164  1.347530 -0.861760  0.065240  0.005120
3rd -0.202618  0.065341 -0.768141  1.011570 -0.963761
4th  0.074309  1.732945 -0.793758 -0.636165 -0.883917
5th  0.378552 -0.541739  0.673559  1.352167  1.087960 

  index         a         b         c         d         e
0   1st -2.265936 -1.657913 -1.548239 -1.010342 -0.670365
1   2nd  0.245164  1.347530 -0.861760  0.065240  0.005120
2   3rd -0.202618  0.065341 -0.768141  1.011570 -0.963761
3   4th  0.074309  1.732945 -0.793758 -0.636165 -0.883917
4   5th  0.378552 -0.541739  0.673

In [34]:
#reset_index(inplace=)
import numpy as np
import pandas as pd
df1=pd.DataFrame(np.random.randn(5,5),index=['1st','2nd','3rd','4th','5th'],columns=['a','b','c','d','e'])
df1.reset_index(inplace=True)
print(df1)

  index         a         b         c         d         e
0   1st -0.087477 -0.630029 -0.744434 -0.159646 -1.096970
1   2nd  0.973789  1.291243  0.018437 -0.366334 -1.084760
2   3rd -0.178933 -0.324224  1.002707  2.173113  1.037584
3   4th -0.840685 -0.979378 -0.904631 -0.837036  1.095020
4   5th -0.822134 -0.992611 -1.205441  0.290795  0.676913


In [42]:
#drop() with inplace
import numpy as np
import pandas as pd
df1=pd.DataFrame(np.random.randn(5,5),index=['1st','2nd','3rd','4th','5th'],columns=['a','b','c','d','e'])
df1.drop('a',axis=1,inplace=True)
print(df1,'\n')
df1.drop('1st',axis=0,inplace=True)
print(df1)

            b         c         d         e
1st  0.348843  1.320456 -0.808753 -0.477658
2nd -1.418483  0.038763 -0.778430 -0.197913
3rd  0.008653 -0.426342 -0.297626 -1.062914
4th  0.845329  0.372320  0.927811  0.095937
5th -1.601596  0.212879  0.575639  2.289974 

            b         c         d         e
2nd -1.418483  0.038763 -0.778430 -0.197913
3rd  0.008653 -0.426342 -0.297626 -1.062914
4th  0.845329  0.372320  0.927811  0.095937
5th -1.601596  0.212879  0.575639  2.289974


In [49]:
#assigning new names to indexex
import numpy as np
import pandas as pd
df1=pd.DataFrame(np.random.randn(5,5),index=['1st','2nd','3rd','4th','5th'],columns=['a','b','c','d','e'])
df1['new index']=[1,2,3,4,5]
print(df1.set_index('new index'),'\n')
print(df1,'\n')
print(df1.set_index('new index',inplace=True),'\n') #returns NONE as output #MY INFERENCE: Functions dont return values with inplace
print(df1,'\n')

                  a         b         c         d         e
new index                                                  
1          1.288535 -0.351995 -0.953901  0.036447 -0.970422
2         -2.105781 -0.606712 -0.171509 -0.394214 -0.886809
3          0.215698 -0.134027  0.924576 -0.205672  0.124401
4          0.470597 -0.153957  0.970852 -1.351109  0.000757
5         -1.974571 -1.436229  0.172202 -0.794337 -1.131699 

            a         b         c         d         e  new index
1st  1.288535 -0.351995 -0.953901  0.036447 -0.970422          1
2nd -2.105781 -0.606712 -0.171509 -0.394214 -0.886809          2
3rd  0.215698 -0.134027  0.924576 -0.205672  0.124401          3
4th  0.470597 -0.153957  0.970852 -1.351109  0.000757          4
5th -1.974571 -1.436229  0.172202 -0.794337 -1.131699          5 

None 

                  a         b         c         d         e
new index                                                  
1          1.288535 -0.351995 -0.953901  0.036447 -0.970422

In [4]:
#combining DataFrames by concat()
import pandas as pd
import numpy as np
df1=pd.DataFrame({'Customer':['qwe','wer','ert','rty'],
                  'Sales':[1,2,3,4],
                  'ID':['qw','er','ty','yu'],      ##note 't' and 'ty'
                  'Important':['yes','no','yes','no']})
df2=pd.DataFrame({'Customer':['qwe','wer','ert','rty'],
                  'Discount':[10,20,30,40],
                  'ID':['qw','er','t','yu'],    #note 't' and 'ty'
                  'Paid':['no','no','yes','yes']})
print(pd.concat([df1,df2]),'\n')   #MY INFERENCE: by default axis=0 and sort=False
print(pd.concat([df1,df2],sort=True),'\n')
print(pd.concat([df1,df2],sort=True,axis=1),'\n')

  Customer  Sales  ID Important  Discount Paid
0      qwe    1.0  qw       yes       NaN  NaN
1      wer    2.0  er        no       NaN  NaN
2      ert    3.0  ty       yes       NaN  NaN
3      rty    4.0  yu        no       NaN  NaN
0      qwe    NaN  qw       NaN      10.0   no
1      wer    NaN  er       NaN      20.0   no
2      ert    NaN   t       NaN      30.0  yes
3      rty    NaN  yu       NaN      40.0  yes 

  Customer  Discount  ID Important Paid  Sales
0      qwe       NaN  qw       yes  NaN    1.0
1      wer       NaN  er        no  NaN    2.0
2      ert       NaN  ty       yes  NaN    3.0
3      rty       NaN  yu        no  NaN    4.0
0      qwe      10.0  qw       NaN   no    NaN
1      wer      20.0  er       NaN   no    NaN
2      ert      30.0   t       NaN  yes    NaN
3      rty      40.0  yu       NaN  yes    NaN 

  Customer  Sales  ID Important Customer  Discount  ID Paid
0      qwe      1  qw       yes      qwe        10  qw   no
1      wer      2  er        n

In [6]:
#combining DataFrames by concat()
import pandas as pd
import numpy as np
df1=pd.DataFrame({'Customer':['qwe','wer','ert','rty'],
                  'Sales':[1,2,3,4],
                  'ID':['qw','er','ty','yu'],      ##note 't' and 'ty'
                  'Important':['yes','no','yes','no']},index=[1,2,3,4])
df2=pd.DataFrame({'Customer':['qwe','wer','ert','rty'],
                  'Discount':[10,20,30,40],
                  'ID':['qw','er','t','yu'],    #note 't' and 'ty'
                  'Paid':['no','no','yes','yes']},index=[5,6,7,8])
print(pd.concat([df1,df2]),'\n')   #MY INFERENCE: by default axis=0 and sort=False
print(pd.concat([df1,df2],sort=True),'\n')
print(pd.concat([df1,df2],sort=True,axis=1),'\n')

  Customer  Sales  ID Important  Discount Paid
1      qwe    1.0  qw       yes       NaN  NaN
2      wer    2.0  er        no       NaN  NaN
3      ert    3.0  ty       yes       NaN  NaN
4      rty    4.0  yu        no       NaN  NaN
5      qwe    NaN  qw       NaN      10.0   no
6      wer    NaN  er       NaN      20.0   no
7      ert    NaN   t       NaN      30.0  yes
8      rty    NaN  yu       NaN      40.0  yes 

  Customer  Discount  ID Important Paid  Sales
1      qwe       NaN  qw       yes  NaN    1.0
2      wer       NaN  er        no  NaN    2.0
3      ert       NaN  ty       yes  NaN    3.0
4      rty       NaN  yu        no  NaN    4.0
5      qwe      10.0  qw       NaN   no    NaN
6      wer      20.0  er       NaN   no    NaN
7      ert      30.0   t       NaN  yes    NaN
8      rty      40.0  yu       NaN  yes    NaN 

  Customer  Sales   ID Important Customer  Discount   ID Paid
1      qwe    1.0   qw       yes      NaN       NaN  NaN  NaN
2      wer    2.0   er    

In [11]:
#merge
import pandas as pd
import numpy as np
df1=pd.DataFrame({'Customer':['qwe','wer','ert','rts'],
                  'Sales':[1,2,3,4],
                  'ID':['qw','er','ty','yu'],      ##note 't' and 'ty'
                  'Important':['yes','no','yes','no']},index=[1,2,3,4])
df2=pd.DataFrame({'Customer':['qwe','wee','ert','rts'],
                  'Discount':[10,20,30,40],
                  'ID':['qw','er','t','yu'],    #note 't' and 'ty'
                  'Paid':['no','no','yes','yes']},index=[5,6,7,8])
print(pd.merge(df1,df2,how='outer',on='Customer'),'\n')
print(pd.merge(df1,df2,how='inner',on='Customer'),'\n')
print(pd.merge(df1,df2,how='left',on='Customer'),'\n')
print(pd.merge(df1,df2,how='right',on='Customer'),'\n')

  Customer  Sales ID_x Important  Discount ID_y Paid
0      qwe    1.0   qw       yes      10.0   qw   no
1      wer    2.0   er        no       NaN  NaN  NaN
2      ert    3.0   ty       yes      30.0    t  yes
3      rts    4.0   yu        no      40.0   yu  yes
4      wee    NaN  NaN       NaN      20.0   er   no 

  Customer  Sales ID_x Important  Discount ID_y Paid
0      qwe      1   qw       yes        10   qw   no
1      ert      3   ty       yes        30    t  yes
2      rts      4   yu        no        40   yu  yes 

  Customer  Sales ID_x Important  Discount ID_y Paid
0      qwe      1   qw       yes      10.0   qw   no
1      wer      2   er        no       NaN  NaN  NaN
2      ert      3   ty       yes      30.0    t  yes
3      rts      4   yu        no      40.0   yu  yes 

  Customer  Sales ID_x Important  Discount ID_y Paid
0      qwe    1.0   qw       yes        10   qw   no
1      wee    NaN  NaN       NaN        20   er   no
2      ert    3.0   ty       yes        

In [20]:
#join
import numpy as np
import pandas as pd
df1=pd.DataFrame({'Q1':[11,12,13],'Q2':[21,22,23]},index=['i1','i2','i3'])
df2=pd.DataFrame({'Q3':[31,32,33],'Q4':[41,42,43]},index=['i1','i2','i4'])
print(df1.join(df2,how='outer'))
print(df1.join(df2,how='inner'))
print(df1.join(df2,how='right'))
print(df1.join(df2,how='left'))

      Q1    Q2    Q3    Q4
i1  11.0  21.0  31.0  41.0
i2  12.0  22.0  32.0  42.0
i3  13.0  23.0   NaN   NaN
i4   NaN   NaN  33.0  43.0
    Q1  Q2  Q3  Q4
i1  11  21  31  41
i2  12  22  32  42
      Q1    Q2  Q3  Q4
i1  11.0  21.0  31  41
i2  12.0  22.0  32  42
i4   NaN   NaN  33  43
    Q1  Q2    Q3    Q4
i1  11  21  31.0  41.0
i2  12  22  32.0  42.0
i3  13  23   NaN   NaN


In [36]:
#unique()
import numpy as np
import pandas as pd
df7 = pd.DataFrame({"customer":['101','102','103','104'], 
                    'category': ['cat2','cat2','cat1','cat3'],
                    'important': ['yes','no','yes','yes'],
                    'sales': [123,52,214,663]},index=[0,1,2,3])

df8 = pd.DataFrame({"customer":['101','103','104','105'], 
                    'color': ['yellow','green','green','blue'],
                    'distance': [12,9,44,21],
                    'sales': [123,214,663,331]},index=[4,5,6,7])
print(df8['color'].unique(),'\n')
print(df8['color'].value_counts(),'\n')
print(df8['distance'].mean(),'\n')
print(df8.columns)

['yellow' 'green' 'blue'] 

green     2
blue      1
yellow    1
Name: color, dtype: int64 

21.5 

Index(['customer', 'color', 'distance', 'sales'], dtype='object')


In [1]:
import numpy as np
import pandas as pd
df7 = pd.DataFrame({"customer":['101','102','103','104'], 
                    'category': ['cat2','cat2','cat1','cat3'],
                    'important': ['yes','no','yes','yes'],
                    'sales': [123,52,214,663]},index=[0,1,2,3])

df8 = pd.DataFrame({"customer":['101','103','104','105'], 
                    'color': ['yellow','green','green','blue'],
                    'distance': [12,9,44,21],
                    'sales': [123,214,663,331]},index=[4,5,6,7])
df=df8[(df8['customer']!='101') & (df8['customer']!='103')]
print(df,'\n')
print(df['sales'].mean(),'\n')
print(df['sales'].min(),'\n')
print(df['sales'].max(),'\n')
print(df['sales'].std(),'\n')

  customer  color  distance  sales
6      104  green        44    663
7      105   blue        21    331 

497.0 

331 

663 

234.75945135393377 



In [7]:
#defining new functions
import numpy as np
import pandas as pd
df7 = pd.DataFrame({"customer":['101','102','103','104'], 
                    'category': ['cat2','cat2','cat1','cat3'],
                    'important': ['yes','no','yes','yes'],
                    'sales': [123,52,214,663]},index=[0,1,2,3])

df8 = pd.DataFrame({"customer":['101','103','104','105'], 
                    'color': ['yellow','green','green','blue'],
                    'distance': [12,9,44,21],
                    'sales': [123,214,663,331]},index=[4,5,6,7])
def profit(s):
    return s*0.5
print(df8['sales'].apply(profit),'\n')
print(df8['color'].apply(len),'\n')

4     61.5
5    107.0
6    331.5
7    165.5
Name: sales, dtype: float64 

4    6
5    5
6    5
7    4
Name: color, dtype: int64 



In [4]:
#applymap()
import numpy as np
import pandas as pd
df8 = pd.DataFrame({"customer":['101','103','104','105'], 
                    'color': ['yellow','green','green','blue'],
                    'distance': [12,9,44,21],
                    'sales': [123,214,663,331]},index=[4,5,6,7])
def profit(s):
    return s*0.5
df=df8[['distance','sales']]
print(df,'\n')
print(df.apply(profit))

   distance  sales
4        12    123
5         9    214
6        44    663
7        21    331 

   distance  sales
4       6.0   61.5
5       4.5  107.0
6      22.0  331.5
7      10.5  165.5


In [14]:
#defining own functions
import numpy as np
import pandas as pd
df8 = pd.DataFrame({"customer":['101','103','104','105'], 
                    'color': ['yellow','green','green','blue'],
                    'distance': [12,9,44,21],
                    'sales': [123,214,663,331]},index=[4,5,6,7])
def sum1(s):
    return sum(s)
df=df8[['distance','sales']]
print(df,'\n')
print(df.sum(),'\n')
print(df.apply(sum1))
print(df.applymap(sum1))   #returns error as applymap() works entry by entry

   distance  sales
4        12    123
5         9    214
6        44    663
7        21    331 

distance      86
sales       1331
dtype: int64 

distance      86
sales       1331
dtype: int64


TypeError: 'int' object is not iterable

In [23]:
#del command and other functions
import numpy as np
import pandas as pd
df8 = pd.DataFrame({"customer":['101','103','104','105'], 
                    'color': ['yellow','green','green','blue'],
                    'distance': [12,9,44,21],
                    'sales': [123,214,663,331]},index=[4,5,6,7])
del df8['color']
print(df8.index,'\n')
print(df8.sort_values(by='distance'),'\n')
print(df8.sort_values(by='distance',inplace=True))

Int64Index([4, 5, 6, 7], dtype='int64') 

  customer  distance  sales
5      103         9    214
4      101        12    123
7      105        21    331
6      104        44    663 

None


In [35]:
#grouping data
mydict = {'customer': ['Customer 1','Customer 1','Customer2','Customer2','Customer3','Customer3'], 
          'product1': [1.1,2.1,3.8,4.2,5.5,6.9],
          'product2': [8.2,9.1,11.1,5.2,44.66,983]}
df6 = pd.DataFrame(mydict,index=['Purchase 1','Purchase 2','Purchase 3','Purchase 4','Purchase 5','Purchase 6'])

grouped_data = df6.groupby('customer')
grouped_data.describe()

product1                                           product2  \
              count mean       std  min   25%  50%   75%  max    count   
customer                                                                 
Customer 1      2.0  1.6  0.707107  1.1  1.35  1.6  1.85  2.1      2.0   
Customer2       2.0  4.0  0.282843  3.8  3.90  4.0  4.10  4.2      2.0   
Customer3       2.0  6.2  0.989949  5.5  5.85  6.2  6.55  6.9      2.0   

                                                                        
              mean         std    min      25%     50%      75%    max  
customer                                                                
Customer 1    8.65    0.636396   8.20    8.425    8.65    8.875    9.1  
Customer2     8.15    4.171930   5.20    6.675    8.15    9.625   11.1  
Customer3   513.83  663.506577  44.66  279.245  513.83  748.415  983.0

In [38]:
mydict = {'customer': ['Customer 1','Customer 1','Customer2','Customer2','Customer3','Customer3'], 
          'product1': [1.1,2.1,3.8,4.2,5.5,6.9],
          'product2': [8.2,9.1,11.1,5.2,44.66,983]}
df6 = pd.DataFrame(mydict,index=['Purchase 1','Purchase 2','Purchase 3','Purchase 4','Purchase 5','Purchase 6'])

grouped_data = df6.groupby('customer')
print(grouped_data.describe(),'\n')
print(grouped_data.max(),'\n')
print(grouped_data.std(),'\n')

           product1                                           product2  \
              count mean       std  min   25%  50%   75%  max    count   
customer                                                                 
Customer 1      2.0  1.6  0.707107  1.1  1.35  1.6  1.85  2.1      2.0   
Customer2       2.0  4.0  0.282843  3.8  3.90  4.0  4.10  4.2      2.0   
Customer3       2.0  6.2  0.989949  5.5  5.85  6.2  6.55  6.9      2.0   

                                                                        
              mean         std    min      25%     50%      75%    max  
customer                                                                
Customer 1    8.65    0.636396   8.20    8.425    8.65    8.875    9.1  
Customer2     8.15    4.171930   5.20    6.675    8.15    9.625   11.1  
Customer3   513.83  663.506577  44.66  279.245  513.83  748.415  983.0   

            product1  product2
customer                      
Customer 1       2.1       9.1
Customer2        4.2  

In [43]:
#saving and loading dataframes to csv files
df8.to_csv('df8.csv',index=True)
newdf8=pd.read_csv('df8.csv',index_col=0)
print(newdf8,'\n')
newdf8=pd.read_csv('df8.csv',index_col=1)
print(newdf8,'\n')
newdf8=pd.read_csv('df8.csv')
print(newdf8,'\n')

   customer  distance  sales
5       103         9    214
4       101        12    123
7       105        21    331
6       104        44    663 

          Unnamed: 0  distance  sales
customer                             
103                5         9    214
101                4        12    123
105                7        21    331
104                6        44    663 

   Unnamed: 0  customer  distance  sales
0           5       103         9    214
1           4       101        12    123
2           7       105        21    331
3           6       104        44    663 



In [47]:
##saving and loading dataframes to excel files
df8.to_excel('df8.xlsx',index=False)
newdf8=pd.read_excel('df8.xlsx')
print(newdf8,'\n')
newdf8=pd.read_excel('df8.xlsx',index_col=0)
print(newdf8,'\n')
df8.to_excel('df8.xlsx',index=True)
newdf8=pd.read_excel('df8.xlsx')
print(newdf8,'\n')
newdf8=pd.read_excel('df8.xlsx',index_col=0)
print(newdf8,'\n')
newdf8=pd.read_excel('df8.xlsx',index_col=1)
print(newdf8,'\n')

   customer  distance  sales
0       103         9    214
1       101        12    123
2       105        21    331
3       104        44    663 

          distance  sales
customer                 
103              9    214
101             12    123
105             21    331
104             44    663 

   Unnamed: 0  customer  distance  sales
0           5       103         9    214
1           4       101        12    123
2           7       105        21    331
3           6       104        44    663 

   customer  distance  sales
5       103         9    214
4       101        12    123
7       105        21    331
6       104        44    663 

          Unnamed: 0  distance  sales
customer                             
103                5         9    214
101                4        12    123
105                7        21    331
104                6        44    663 



In [57]:
#accessing NumPy arrays with logicals
import numpy as np
a1=np.random.randn(15)
print(a1,'\n')
print(a1>0,'\n')
print(type(a1>0),'\n')
print(a1[a1>0],'\n')
print(type(a1[a1>0]),'\n')

[-0.9389958   0.42892925  0.29673096 -0.31851128 -0.14212119 -0.02038357
  1.27338963 -1.0967013   1.40159369  1.13466771 -2.32408336  0.30793096
 -1.2282552   0.02528246 -0.78390301] 

[False  True  True False False False  True False  True  True False  True
 False  True False] 

<class 'numpy.ndarray'> 

[0.42892925 0.29673096 1.27338963 1.40159369 1.13466771 0.30793096
 0.02528246] 

<class 'numpy.ndarray'> 



In [59]:
#changing values by logicals
r1=np.random.randn(15)
print(r1,'\n')
r1[r1>0.5]=-5
print(r1,'\n')

[ 0.76125097  0.33480664 -1.75148067  0.02600096  0.52885886 -2.44167233
  1.28368787  0.51684982  0.31383327  1.41712245 -0.82257496  0.19242036
 -0.3042825   0.95242325 -0.02033472] 

[-5.          0.33480664 -1.75148067  0.02600096 -5.         -2.44167233
 -5.         -5.          0.31383327 -5.         -0.82257496  0.19242036
 -0.3042825  -5.         -0.02033472] 



In [68]:
#saving and loading as .npy and .npz
r1=np.random.randn(15)
r2=np.random.randn(15)
np.save('savedfile',r1,r2)
np.savez('savedzfile',a1=r1,a2=r2)
print(np.load('savedfile.npy'),'\n')
print(np.load('savedzfile.npz'),'\n')
l1=np.load('savedzfile.npz')
print(l1['a1'],'\n')
print(l1['a2'],'\n')
n1=l1['a2']
print(n1)

[-0.30851087 -0.04005046 -0.94280825 -0.81085768  0.49610995 -1.68700881
 -0.75629143  1.22687978  1.0473703   1.05386365  0.21269222  1.39165876
  0.32192738 -0.86832786  1.42342225] 


[-0.30851087 -0.04005046 -0.94280825 -0.81085768  0.49610995 -1.68700881
 -0.75629143  1.22687978  1.0473703   1.05386365  0.21269222  1.39165876
  0.32192738 -0.86832786  1.42342225] 

[ 0.55586372  0.9757939   0.17802237 -0.70083611 -1.32388057 -0.55210869
 -1.13668574  0.40847391 -1.76860305  0.20273121 -0.05460155 -0.12377503
 -0.79412372  0.92903318 -1.21416954] 

[ 0.55586372  0.9757939   0.17802237 -0.70083611 -1.32388057 -0.55210869
 -1.13668574  0.40847391 -1.76860305  0.20273121 -0.05460155 -0.12377503
 -0.79412372  0.92903318 -1.21416954]


In [80]:
#save/load as txt files
np.savetxt('fname',r1)
l1=np.loadtxt('fname')
l1

array([-0.30851087, -0.04005046, -0.94280825, -0.81085768,  0.49610995,
       -1.68700881, -0.75629143,  1.22687978,  1.0473703 ,  1.05386365,
        0.21269222,  1.39165876,  0.32192738, -0.86832786,  1.42342225])