In [44]:
import numpy as np
n1=np.array([1,2,3,8])
n2=np.array([4,5,6,7])
print(np.vstack((n1,n2)))
print(np.hstack((n1,n2)))
print(np.column_stack((n1,n2)))
n3=np.column_stack((n1,n2))
print(n3)
type(n3)

[[1 2 3 8]
 [4 5 6 7]]
[1 2 3 8 4 5 6 7]
[[1 4]
 [2 5]
 [3 6]
 [8 7]]
[[1 4]
 [2 5]
 [3 6]
 [8 7]]


numpy.ndarray

In [56]:
n1=np.array([1,2,3,4,5,6])
n2=np.array([4,5,6,7,8,9])
print(np.intersect1d(n1,n2))
print(np.setdiff1d(n1,n2))
print(np.setdiff1d(n2,n1))
n3=np.intersect1d(n1,n2)
print(type(n3))
n4=np.setdiff1d(n2,n1)
print(type(n4))

[4 5 6]
[1 2 3]
[7 8 9]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [71]:
n1=np.array([1,2,3,4])
n2=np.array([5,6,7,8])
print(np.sum((n1,n2)))
print(np.sum((n1,n2),axis=0))
print(np.sum((n1,n2),axis=1))
n3=np.sum((n1,n2))
print(type(n3))
type(np.sum((n1,n2),axis=1))

36
[ 6  8 10 12]
[10 26]
<class 'numpy.int32'>


numpy.ndarray

In [85]:
n1=np.array([10,20,30])
n1-=2
print(type(n1))

<class 'numpy.ndarray'>


In [108]:
n1=np.array([1000,1500,10])
print(np.median(n1))
print(np.mean(n1))
print(np.std(n1))

1000.0
836.6666666666666
619.157133170212


In [110]:
#saving and loading numpy arrays
np.save('new_numpy',n1)
n2=np.load('new_numpy.npy')
print(n2)
print(type(n2))

[1000 1500   10]
<class 'numpy.ndarray'>


In [8]:
#changing index in list
import pandas as pd
a1=[11,2,5,9]
s1=pd.Series(['qwe',1,3,'but',5,6],index=[10,6,9,'10','nut','cut'])
print(type(s1))
s1

<class 'pandas.core.series.Series'>


10     qwe
6        1
9        3
10     but
nut      5
cut      6
dtype: object

In [15]:
#changing index in dictionary
s2=pd.Series({'a':2.9,1:4.7,'acd':3.0})
s2

a      2.9
1      4.7
acd    3.0
dtype: float64

In [22]:
#changing index positions
s2=pd.Series({'a':2.9,1:4.7,'acd':3.0},index=['acd',1,'q','a'])
s2

acd    3.0
1      4.7
q      NaN
a      2.9
dtype: float64

In [33]:
#extracting single element and sequeence of elements from front & back
import pandas
s1=pandas.Series([1,2,3,4,5,6,7,8,9])
print(s1[3])
print(s1[:7])
print(s1[-4:])

4
0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64
5    6
6    7
7    8
8    9
dtype: int64


In [41]:
#adding scalar value to series elements and adding 2 series objects
#operations other than addition can also be done
s1=pd.Series([1,2,3,4])
print(s1+5)
print(type(s1+5))
s2=pd.Series([10,20,30,40])
print(s2+s1)
print(type(s1+s2))
print(s2/s1)

0    6
1    7
2    8
3    9
dtype: int64
<class 'pandas.core.series.Series'>
0    11
1    22
2    33
3    44
dtype: int64
<class 'pandas.core.series.Series'>
0    10.0
1    10.0
2    10.0
3    10.0
dtype: float64


In [65]:
#creating a dataframe
s2=pd.DataFrame({'Name':['Jit','G2','Guddu'],'Marks':[99,100,98]})
print(s2)

    Name  Marks
0    Jit     99
1     G2    100
2  Guddu     98


In [89]:
#fetch working directory
import os
print(os.getcwd())

C:\Users\G2\Desktop


In [100]:
#head(),tail(),shape and describe functions
import pandas as pd
iris=pd.read_csv('iris.csv') #reading a file from working directory
print(iris.head())
print(iris.tail())
print(iris.shape)
print(iris.describe())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Ir

In [96]:
#iloc[]
print(iris.iloc[100:115,3:6])

     PetalLengthCm  PetalWidthCm         Species
100            6.0           2.5  Iris-virginica
101            5.1           1.9  Iris-virginica
102            5.9           2.1  Iris-virginica
103            5.6           1.8  Iris-virginica
104            5.8           2.2  Iris-virginica
105            6.6           2.1  Iris-virginica
106            4.5           1.7  Iris-virginica
107            6.3           1.8  Iris-virginica
108            5.8           1.8  Iris-virginica
109            6.1           2.5  Iris-virginica
110            5.1           2.0  Iris-virginica
111            5.3           1.9  Iris-virginica
112            5.5           2.1  Iris-virginica
113            5.0           2.0  Iris-virginica
114            5.1           2.4  Iris-virginica


In [106]:
#loc[]
print(iris.loc[5:16,('Species','PetalLengthCm')])

        Species  PetalLengthCm
5   Iris-setosa            1.7
6   Iris-setosa            1.4
7   Iris-setosa            1.5
8   Iris-setosa            1.4
9   Iris-setosa            1.5
10  Iris-setosa            1.5
11  Iris-setosa            1.6
12  Iris-setosa            1.4
13  Iris-setosa            1.1
14  Iris-setosa            1.2
15  Iris-setosa            1.5
16  Iris-setosa            1.3


In [115]:
#dropping columns and rows
print(iris.drop('PetalLengthCm',axis=1))
print('                               ')
print('                               ')
print(iris.drop([1,2,3],axis=0))
print('                               ')
print('                               ')
print(iris.head())

      Id  SepalLengthCm  SepalWidthCm  PetalWidthCm         Species
0      1            5.1           3.5           0.2     Iris-setosa
1      2            4.9           3.0           0.2     Iris-setosa
2      3            4.7           3.2           0.2     Iris-setosa
3      4            4.6           3.1           0.2     Iris-setosa
4      5            5.0           3.6           0.2     Iris-setosa
..   ...            ...           ...           ...             ...
145  146            6.7           3.0           2.3  Iris-virginica
146  147            6.3           2.5           1.9  Iris-virginica
147  148            6.5           3.0           2.0  Iris-virginica
148  149            6.2           3.4           2.3  Iris-virginica
149  150            5.9           3.0           1.8  Iris-virginica

[150 rows x 5 columns]
                               
                               
      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1   

In [120]:
#mean(),median(),min(),max()
print(iris.mean())
print(iris.median())
print(iris.min())
print(iris.max())

Id               75.500000
SepalLengthCm     5.843333
SepalWidthCm      3.054000
PetalLengthCm     3.758667
PetalWidthCm      1.198667
dtype: float64
Id               75.50
SepalLengthCm     5.80
SepalWidthCm      3.00
PetalLengthCm     4.35
PetalWidthCm      1.30
dtype: float64
Id                         1
SepalLengthCm            4.3
SepalWidthCm               2
PetalLengthCm              1
PetalWidthCm             0.1
Species          Iris-setosa
dtype: object
Id                          150
SepalLengthCm               7.9
SepalWidthCm                4.4
PetalLengthCm               6.9
PetalWidthCm                2.5
Species          Iris-virginica
dtype: object


In [126]:
#doubling particular columns
def double_make(s):
    return s*2
print(iris[['SepalWidthCm','PetalWidthCm']].apply(double_make))

     SepalWidthCm  PetalWidthCm
0             7.0           0.4
1             6.0           0.4
2             6.4           0.4
3             6.2           0.4
4             7.2           0.4
..            ...           ...
145           6.0           4.6
146           5.0           3.8
147           6.0           4.0
148           6.8           4.6
149           6.0           3.6

[150 rows x 2 columns]


In [131]:
#value_counts() and sort_values()
print(iris['Species'].value_counts())
print(iris.sort_values(by='SepalWidthCm'))
print(iris.sort_values(by='Species'))

Iris-versicolor    50
Iris-virginica     50
Iris-setosa        50
Name: Species, dtype: int64
      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
60    61            5.0           2.0            3.5           1.0   
62    63            6.0           2.2            4.0           1.0   
119  120            6.0           2.2            5.0           1.5   
68    69            6.2           2.2            4.5           1.5   
41    42            4.5           2.3            1.3           0.3   
..   ...            ...           ...            ...           ...   
16    17            5.4           3.9            1.3           0.4   
14    15            5.8           4.0            1.2           0.2   
32    33            5.2           4.1            1.5           0.1   
33    34            5.5           4.2            1.4           0.2   
15    16            5.7           4.4            1.5           0.4   

             Species  
60   Iris-versicolor  
62   Iris-versicolo