In [2]:
#NumPy 1D Array
import numpy
n1=numpy.array([1,2,3])
print(n1,type(n1))

[1 2 3] <class 'numpy.ndarray'>


In [4]:
#NumPy 2D Array
import numpy
n1=numpy.array([[1,2,3],[4,5,6]])
print(n1,type(n1))

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>


In [6]:
#zeros Method
import numpy as np
n1=np.zeros((4,3))
print(n1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
#full Method
import numpy as np
n1=np.full((4,3),56)
print(n1)

[[56 56 56]
 [56 56 56]
 [56 56 56]
 [56 56 56]]


In [9]:
#arange Method
import numpy as np
n1=np.arange(0,101,10)
print(n1)

[  0  10  20  30  40  50  60  70  80  90 100]


In [82]:
#random method, randint sub-method
import numpy as np
n1=np.random.randint(0,100,4)
print(n1)

[71 65 82 31]


In [87]:
#shape method
import numpy as np
n1=np.array([[1,2,3],[4,5,6],[7,8,9],[3,6,5]])
n1.shape=(6,2)
n1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 3],
       [6, 5]])

In [112]:
#Stacking by vstack(), hstack(), columnstack()
import numpy as np
n1=np.array([1,2,3,4])
n2=np.array([5,6,7,8])
print(np.vstack((n1,n2)),type(np.vstack((n1,n2))),np.shape(np.vstack((n1,n2))))#returns stacked array,its type and its dimensions
print(np.hstack((n1,n2)),type(np.hstack((n1,n2))),np.shape(np.hstack((n1,n2))))
print(np.column_stack((n1,n2)),type(np.column_stack((n1,n2))),np.shape(np.column_stack((n1,n2))))

[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'> (2, 4)
[1 2 3 4 5 6 7 8] <class 'numpy.ndarray'> (8,)
[[1 5]
 [2 6]
 [3 7]
 [4 8]] <class 'numpy.ndarray'> (4, 2)


In [123]:
#NumPy intersection and difference
import numpy as np
n1=np.array([1,2,3,4,5,6,7])
n2=np.array([3,4,5,6,7,8,9])
print(np.intersect1d(n1,n2),type(np.intersect1d(n1,n2)),np.shape(np.intersect1d(n1,n2)))
print(np.setdiff1d(n1,n2),type(np.setdiff1d(n1,n2)),np.shape(np.setdiff1d(n1,n2)))            
print(np.setdiff1d(n2,n1),type(np.setdiff1d(n2,n1)),np.shape(np.setdiff1d(n2,n1)))

[3 4 5 6 7] <class 'numpy.ndarray'> (5,)
[1 2] <class 'numpy.ndarray'> (2,)
[8 9] <class 'numpy.ndarray'> (2,)


In [136]:
#NumPy Array Mathematics
import numpy as np
n1=np.array([1,2,3,4,5,6,7])
n2=np.array([3,4,5,6,7,8,9])
n1+=1
print(n1)
n2-=1
print(n2)
n1*=2
print(n1)
n2=n2/2  #  "n2/=2" confuses the kernel and it returns error
print(n2)

[2 3 4 5 6 7 8]
[2 3 4 5 6 7 8]
[ 4  6  8 10 12 14 16]
[1.  1.5 2.  2.5 3.  3.5 4. ]


In [144]:
#Math Functions
import numpy as np
n1=np.array([1,2,3,4,5,6,7,8,9])
print(np.mean(n1))
print(np.median(n1))
print(np.std(n1))
print(n1.mean())                    # this syntax only valid for mean and standard deviation, not median
print(n1.std())                     # this syntax only valid for mean and standard deviation, not median

5.0
5.0
2.581988897471611
5.0
2.581988897471611


In [152]:
#save and load NumPy array
n1=['Jitendra','Male',27,'Data Analyst','Microsoft',2500]
print(type(n1))
import numpy as np
n2=np.array(n1)
np.save('new1',n1)
np.save('new2',n2)
n3=np.load('new1.npy')
print(n3,type(n3))
n4=np.load('new2.npy')
print(n4,type(n4))

<class 'list'>
['Jitendra' 'Male' '27' 'Data Analyst' 'Microsoft' '2500'] <class 'numpy.ndarray'>
['Jitendra' 'Male' '27' 'Data Analyst' 'Microsoft' '2500'] <class 'numpy.ndarray'>


In [155]:
#save and load NumPy array
n1=['Jitendra','Male',27,'Data Analyst','Microsoft',2500]
print(type(n1))
np.save('new1',n1)
n3=np.load('new1.npy')
print(n3,type(n3))

<class 'list'>
['Jitendra' 'Male' '27' 'Data Analyst' 'Microsoft' '2500'] <class 'numpy.ndarray'>


In [5]:
#Pandas series object, changing index  [in Lists]
n1=[1,2,3,4,5]
import pandas as pd
n2=pd.Series(n1)
print(n2)
n3=pd.Series(n1,index=[1,2,3,4,'hi'])
print(n3)


0    1
1    2
2    3
3    4
4    5
dtype: int64
1     1
2     2
3     3
4     4
hi    5
dtype: int64


In [10]:
#Pandas series object, changing index positions  [in dictionaries]
n1={'a':1,'b':2,'c':3}
import pandas as pd
n2=pd.Series(n1)
print(n2)
print(pd.Series(n1,index=['c','a','b','d']))

a    1
b    2
c    3
dtype: int64
c    3.0
a    1.0
b    2.0
d    NaN
dtype: float64


In [10]:
#Extracting Individual Elements and Sequence of Elements
n1=[1,2,3,4,5,6,7,8,9]
import pandas as pd
n2=pd.Series(n1)
print(n2[5])
print(n2[-7:-3])

6
2    3
3    4
4    5
5    6
dtype: int64


In [13]:
#Basic math operations
a1=[1,2,3,4]
import pandas as pd
s1=pd.Series(a1)
print(s1+5)
print(s1-1)
print(s1*3)
print(s1/2)

0    6
1    7
2    8
3    9
dtype: int64
0    0
1    1
2    2
3    3
dtype: int64
0     3
1     6
2     9
3    12
dtype: int64
0    0.5
1    1.0
2    1.5
3    2.0
dtype: float64


In [24]:
#Creating a DataFrame[ERROR DUE CONVENTIONAL SYNTAX OF DICTIONARY]
d1={'a':1,'b':2,'c':3}
print(d1,type(d1))
import pandas as pd
s1=pd.DataFrame({d1})

{'a': 1, 'b': 2, 'c': 3} <class 'dict'>


TypeError: unhashable type: 'dict'

In [25]:
#Creating a DataFrame
d1={'Name':['bob','mike','mac'],'marks':[20,30,40]}
print(d1,type(d1))
import pandas as pd
s1=pd.DataFrame(d1)
print(s1,type(s1))

{'Name': ['bob', 'mike', 'mac'], 'marks': [20, 30, 40]} <class 'dict'>
   Name  marks
0   bob     20
1  mike     30
2   mac     40 <class 'pandas.core.frame.DataFrame'>


In [39]:
#Analysing a Dataset
import pandas as pd
print(pd.read_csv('4tips.csv').head())
print(pd.read_csv('4tips.csv').tail())
print(pd.read_csv('4tips.csv').shape)
pd.read_csv('4tips.csv').describe()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2
(244, 7)


total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [50]:
#.iloc[]
import pandas as pd
print(pd.read_csv('4tips.csv').iloc[7:19,4:7])

day    time  size
7   Sun  Dinner     4
8   Sun  Dinner     2
9   Sun  Dinner     2
10  Sun  Dinner     2
11  Sun  Dinner     4
12  Sun  Dinner     2
13  Sun  Dinner     4
14  Sun  Dinner     2
15  Sun  Dinner     2
16  Sun  Dinner     3
17  Sun  Dinner     3
18  Sun  Dinner     3

In [53]:
#.loc[]
import pandas as pd
print(pd.read_csv('4tips.csv').loc[7:19,('day','time')])

    day    time
7   Sun  Dinner
8   Sun  Dinner
9   Sun  Dinner
10  Sun  Dinner
11  Sun  Dinner
12  Sun  Dinner
13  Sun  Dinner
14  Sun  Dinner
15  Sun  Dinner
16  Sun  Dinner
17  Sun  Dinner
18  Sun  Dinner
19  Sat  Dinner


In [62]:
#dropping columns
import pandas as pd
print(pd.read_csv('4tips.csv').drop('day',axis=1))
print(pd.read_csv('4tips.csv'))

     total_bill   tip     sex smoker    time  size
0         16.99  1.01  Female     No  Dinner     2
1         10.34  1.66    Male     No  Dinner     3
2         21.01  3.50    Male     No  Dinner     3
3         23.68  3.31    Male     No  Dinner     2
4         24.59  3.61  Female     No  Dinner     4
..          ...   ...     ...    ...     ...   ...
239       29.03  5.92    Male     No  Dinner     3
240       27.18  2.00  Female    Yes  Dinner     2
241       22.67  2.00    Male    Yes  Dinner     2
242       17.82  1.75    Male     No  Dinner     2
243       18.78  3.00  Female     No  Dinner     2

[244 rows x 6 columns]
     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ... 

In [66]:
#dropping rows
import pandas as pd
print(pd.read_csv('4tips.csv').drop([1,2,3,4,5],axis=0))

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
6          8.77  2.00    Male     No   Sun  Dinner     2
7         26.88  3.12    Male     No   Sun  Dinner     4
8         15.04  1.96    Male     No   Sun  Dinner     2
9         14.78  3.23    Male     No   Sun  Dinner     2
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[239 rows x 7 columns]


In [70]:
#Pandas functions
import pandas as pd
tips=pd.read_csv('4tips.csv')
print(tips.mean())
print("********SPACING********SPACING********SPACING********SPACING********SPACING********")
print(tips.median())
print("********SPACING********SPACING********SPACING********SPACING********SPACING********")
print(tips.min())
print("********SPACING********SPACING********SPACING********SPACING********SPACING********")
print(tips.max())

total_bill    19.785943
tip            2.998279
size           2.569672
dtype: float64
********SPACING********SPACING********SPACING********SPACING********SPACING********
total_bill    17.795
tip            2.900
size           2.000
dtype: float64
********SPACING********SPACING********SPACING********SPACING********SPACING********
total_bill      3.07
tip                1
sex           Female
smoker            No
day              Fri
time          Dinner
size               1
dtype: object
********SPACING********SPACING********SPACING********SPACING********SPACING********
total_bill    50.81
tip              10
sex            Male
smoker          Yes
day            Thur
time          Lunch
size              6
dtype: object


In [85]:
#user defined functions
def squares(s):
    return s**2
import pandas as pd
tips=pd.read_csv('4tips.csv')
print(tips[['total_bill','tip']].apply(squares))

     total_bill      tip
0      288.6601   1.0201
1      106.9156   2.7556
2      441.4201  12.2500
3      560.7424  10.9561
4      604.6681  13.0321
..          ...      ...
239    842.7409  35.0464
240    738.7524   4.0000
241    513.9289   4.0000
242    317.5524   3.0625
243    352.6884   9.0000

[244 rows x 2 columns]


In [3]:
#value_counts()
import pandas as pd
tips=pd.read_csv('4tips.csv')
print(tips['size'].value_counts())
print(tips['tip'].value_counts())

2    156
3     38
4     37
5      5
6      4
1      4
Name: size, dtype: int64
2.00    33
3.00    23
4.00    12
5.00    10
2.50    10
        ..
2.83     1
1.58     1
3.71     1
3.35     1
2.18     1
Name: tip, Length: 123, dtype: int64


In [5]:
#sort_values()
import pandas as pd
tips=pd.read_csv('4tips.csv')
print(tips.sort_values(by='total_bill'))

     total_bill    tip     sex smoker   day    time  size
67         3.07   1.00  Female    Yes   Sat  Dinner     1
92         5.75   1.00  Female    Yes   Fri  Dinner     2
111        7.25   1.00  Female     No   Sat  Dinner     1
172        7.25   5.15    Male    Yes   Sun  Dinner     2
149        7.51   2.00    Male     No  Thur   Lunch     2
..          ...    ...     ...    ...   ...     ...   ...
182       45.35   3.50    Male    Yes   Sun  Dinner     3
156       48.17   5.00    Male     No   Sun  Dinner     6
59        48.27   6.73    Male     No   Sat  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
170       50.81  10.00    Male    Yes   Sat  Dinner     3

[244 rows x 7 columns]
