In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("Redwine+Quality.csv")
df

Unnamed: 0  Tartaric Acid  Grape Density  Citric Acid  Residual.sugar  \
0              1            7.4          0.700         0.00             1.9   
1              2            7.8          0.880         0.00             2.6   
2              3            7.8          0.760         0.04             2.3   
3              4           11.2          0.280         0.56             1.9   
4              5            7.4          0.700         0.00             1.9   
...          ...            ...            ...          ...             ...   
1594        1595            6.2          0.600         0.08             2.0   
1595        1596            5.9          0.550         0.10             2.2   
1596        1597            6.3          0.510         0.13             2.3   
1597        1598            5.9          0.645         0.12             2.0   
1598        1599            6.0          0.310         0.47             3.6   

      Sodium chloride  Free.sulfur.dioxide  Bound.sulfur.dioxide  \
0               0.076                 11.0                  34.0   
1               0.098                 25.0                  67.0   
2               0.092                 15.0                  54.0   
3               0.075                 17.0                  60.0   
4               0.076                 11.0                  34.0   
...               ...                  ...                   ...   
1594            0.090                 32.0                  44.0   
1595            0.062                 39.0                  51.0   
1596            0.076                 29.0                  40.0   
1597            0.075                 32.0                  44.0   
1598            0.067                 18.0                  42.0   

      Alcohol Density  PH Levels  Potassium chloride  Alcohol Content  
0             0.99780       3.51                0.56              9.4  
1             0.99680       3.20                0.68              9.8  
2             0.99700       3.26                0.65              9.8  
3             0.99800       3.16                0.58              9.8  
4             0.99780       3.51                0.56              9.4  
...               ...        ...                 ...              ...  
1594          0.99490       3.45                0.58             10.5  
1595          0.99512       3.52                0.76             11.2  
1596          0.99574       3.42                0.75             11.0  
1597          0.99547       3.57                0.71             10.2  
1598          0.99549       3.39                0.66             11.0  

[1599 rows x 12 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Unnamed: 0            1599 non-null   int64  
 1   Tartaric Acid         1599 non-null   float64
 2   Grape Density         1599 non-null   float64
 3   Citric Acid           1599 non-null   float64
 4   Residual.sugar        1599 non-null   float64
 5   Sodium chloride       1599 non-null   float64
 6   Free.sulfur.dioxide   1599 non-null   float64
 7   Bound.sulfur.dioxide  1599 non-null   float64
 8   Alcohol Density       1599 non-null   float64
 9   PH Levels             1599 non-null   float64
 10  Potassium chloride    1599 non-null   float64
 11  Alcohol Content       1599 non-null   float64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [32]:
a1=np.array([1692,1978,1884,2151,2519])
a2=np.array([68,102,110,112,154])
print(np.cov(a1,a2))
print(np.cov(a1))
print(np.cov(a2))

[[97732.7  9107.3]
 [ 9107.3   941.2]]
97732.70000000001
941.2


In [22]:
from scipy.stats import zscore
data_scaled=df.apply(zscore)
data_scaled.drop('Unnamed: 0',axis=1,inplace=True)
data_scaled

Tartaric Acid  Grape Density  Citric Acid  Residual.sugar  \
0         -0.528360       0.961877    -1.391472       -0.453218   
1         -0.298547       1.967442    -1.391472        0.043416   
2         -0.298547       1.297065    -1.186070       -0.169427   
3          1.654856      -1.384443     1.484154       -0.453218   
4         -0.528360       0.961877    -1.391472       -0.453218   
...             ...            ...          ...             ...   
1594      -1.217796       0.403229    -0.980669       -0.382271   
1595      -1.390155       0.123905    -0.877968       -0.240375   
1596      -1.160343      -0.099554    -0.723916       -0.169427   
1597      -1.390155       0.654620    -0.775267       -0.382271   
1598      -1.332702      -1.216849     1.021999        0.752894   

      Sodium chloride  Free.sulfur.dioxide  Bound.sulfur.dioxide  \
0           -0.243707            -0.466193             -0.379133   
1            0.223875             0.872638              0.624363   
2            0.096353            -0.083669              0.229047   
3           -0.264960             0.107592              0.411500   
4           -0.243707            -0.466193             -0.379133   
...               ...                  ...                   ...   
1594         0.053845             1.542054             -0.075043   
1595        -0.541259             2.211469              0.137820   
1596        -0.243707             1.255161             -0.196679   
1597        -0.264960             1.542054             -0.075043   
1598        -0.434990             0.203223             -0.135861   

      Alcohol Density  PH Levels  Potassium chloride  Alcohol Content  
0            0.558274   1.288643           -0.579207        -0.960246  
1            0.028261  -0.719933            0.128950        -0.584777  
2            0.134264  -0.331177           -0.048089        -0.584777  
3            0.664277  -0.979104           -0.461180        -0.584777  
4            0.558274   1.288643           -0.579207        -0.960246  
...               ...        ...                 ...              ...  
1594        -0.978765   0.899886           -0.461180         0.072294  
1595        -0.862162   1.353436            0.601055         0.729364  
1596        -0.533554   0.705508            0.542042         0.541630  
1597        -0.676657   1.677400            0.305990        -0.209308  
1598        -0.666057   0.511130            0.010924         0.541630  

[1599 rows x 11 columns]

In [23]:
from sklearn.decomposition import PCA
pca = PCA(n_components=11, random_state=123)   # 'n_components=12' as we want eigen values for all variables, 'random_state=123' as we want consistent output
pca_transformed = pca.fit_transform(data_scaled)
pca_transformed

array([[-1.61952988,  0.45095009, -1.77445415, ...,  0.00509804,
        -0.26775943,  0.04863012],
       [-0.79916993,  1.85655306, -0.91169017, ..., -0.52070667,
         0.06283285, -0.13814189],
       [-0.74847909,  0.88203886, -1.17139423, ..., -0.08685693,
        -0.18744237, -0.11822866],
       ...,
       [-1.45612897,  0.31174559,  1.12423941, ..., -0.80877339,
         0.24224843, -0.40291033],
       [-2.27051793,  0.97979111,  0.62796456, ..., -0.61224806,
         0.77940384,  0.04092255],
       [-0.42697475, -0.53669021,  1.6289552 , ...,  0.40430898,
         0.77943963, -0.44978056]])

In [24]:
pca.components_

array([[ 0.48931422, -0.23858436,  0.46363166,  0.14610715,  0.21224658,
        -0.03615752,  0.02357485,  0.39535301, -0.43851962,  0.24292133,
        -0.11323207],
       [-0.11050274,  0.27493048, -0.15179136,  0.27208024,  0.14805156,
         0.51356681,  0.56948696,  0.23357549,  0.00671079, -0.03755392,
        -0.38618096],
       [-0.12330157, -0.44996253,  0.23824707,  0.10128338, -0.09261383,
         0.42879287,  0.3224145 , -0.33887135,  0.05769735,  0.27978615,
         0.47167322],
       [-0.22961737,  0.07895978, -0.07941826, -0.37279256,  0.66619476,
        -0.04353782, -0.03457712, -0.17449976, -0.00378775,  0.55087236,
        -0.12218109],
       [-0.08261366,  0.21873452, -0.05857268,  0.73214429,  0.2465009 ,
        -0.15915198, -0.22246456,  0.15707671,  0.26752977,  0.22596222,
         0.35068141],
       [ 0.10147858,  0.41144893,  0.06959338,  0.04915555,  0.30433857,
        -0.01400021,  0.13630755, -0.3911523 , -0.52211645, -0.38126343,
         0.361

In [33]:
pca.explained_variance_

array([3.10107182, 1.92711489, 1.55151379, 1.21399175, 0.95989238,
       0.66002104, 0.58415655, 0.42322138, 0.34485779, 0.18144664,
       0.05959558])

In [34]:
pca.explained_variance_ratio_

array([0.28173931, 0.1750827 , 0.1409585 , 0.11029387, 0.08720837,
       0.05996439, 0.05307193, 0.03845061, 0.0313311 , 0.01648483,
       0.00541439])